#!/bin/bash

# 格式化具体文件，需要提前安装好clang-format
format_file() {
  file="${1}"
  if [ -f $file ]; then
    clang-format -i ${1}
    git add ${1}
  fi
}

case "${1}" in
  * )
  	# 格式化修改的文件
    for file in `git diff-index --cached --name-only HEAD | grep -iE '\.(cpp|cc|h|hpp)$' ` ; do
      format_file "${file}"
    done
    ;;
esac